import DashboardLayoutBranding from '../ui/components/Dashboard';

export const metadata = {
    title: 'Home',
    description: 'Generated by Next.js',
    icon: "#",
    viewport: {
      width: 'device-width',
      initialScale: 1,
      maximumScale: 1,
    },
  }

export default async function Page() {
      return(
          <main>
              <DashboardLayoutBranding></DashboardLayoutBranding>
          </main>
          );
  }