import DashboardLayoutBranding from '../ui/components/Dashboard';
import { GetAllListsByUser } from '../lib/data';

export const metadata = {
    title: 'Home',
    description: 'Generated by Next.js',
    icon: "#",
    viewport: {
      width: 'device-width',
      initialScale: 1,
      maximumScale: 1,
    },
  }

  

export default async function Page() {
    const lists = await GetAllListsByUser({params: {userId: 1}});
    // console.log(lists);
      return(
          <main>
              <DashboardLayoutBranding data={lists}></DashboardLayoutBranding>
          </main>
          );
  }