import NavBar from './ui/components/NavBar';
import Button from '@mui/material/Button';

export const metadata = {
    title: 'Example Template',
    description: 'Generated by Next.js',
    icon: "#",
    viewport: {
      width: 'device-width',
      initialScale: 1,
      maximumScale: 1,
    },
  }

  // import components
export default async function Page() {
      return(
          <>
  
          <main>
              <h1 >Hello</h1>
              <NavBar></NavBar>
              <img src="" width="400" height="400" alt="random dog image"></img>
          </main>
          </>);
  }